- name: Create Mosquitto password file
  ansible.builtin.file:
    path: /etc/mosquitto/passwd
    state: touch
    owner: mosquitto
    group: mosquitto
    mode: '0600'

- name: Configuring Mosquitto password for authentication
  ansible.builtin.command: mosquitto_passwd -b /etc/mosquitto/passwd {{ mosquitto_username }} {{ mosquitto_password }}

- name: Copy certificates for TLS configuration
  ansible.builtin.copy:
    src: certs
    dest: /etc/mosquitto/
    owner: mosquitto
    group: mosquitto

- name: Fix permissions for certificate keys
  ansible.builtin.shell: find /etc/mosquitto/certs/ -type f | grep "key" | xargs chmod 600

- name: Create Mosquito configuration file from a template
  ansible.builtin.template:
    src: mosquitto_config.j2
    dest: /etc/mosquitto/mosquitto.conf

- name: Create Mosquito Exporter configuration file from a template
  ansible.builtin.template:
    src: mosquitto_exporter_service.j2
    dest: /etc/systemd/system/exporter.service

- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable Firewall ports for SSH
  ansible.builtin.command: firewall-cmd --permanent --add-port=22/tcp

- name: Enable Firewall ports for Mosquitto SSL port
  ansible.builtin.command: firewall-cmd --permanent --add-port={{ ssl_port }}/tcp

- name: Enable Firewall ports for Mosquitto SSL port
  ansible.builtin.command: firewall-cmd --permanent --add-port={{ exporter_port }}/tcp