- name: Stop Mosquitto server
  ansible.builtin.service:
    name: mosquitto
    state: stopped

- name: Reload Firewall
  ansible.builtin.command:  firewall-cmd --reload

- name: Start Mosquitto server
  ansible.builtin.service:
    name: mosquitto
    state: started